DiziInceleme/urls.py
from django.contrib import admin
from django.urls import path, include
from TvShow import views
from django.conf import settings #File Upload
from django.conf.urls.static import static #File Upload


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index" ),
    path('tvshow/', include("TvShow.urls")),
    path('user/', include("User.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 
 #File Upload

TvShow/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "TvShow" #Redirect için gerek

urlpatterns = [
    path('crime/', views.crime, name="crime"),
    path('comedy/', views.comedy, name="comedy"),
    path('mystery/', views.mystery, name="mystery"),
    path('scifi/', views.scifi, name="scifi"),
    path('sport/', views.sport, name="sport"),
    path('detail/<int:id>', views.detail, name="detail"), #<-------
    # path('detail/<str:title>', views.detail, name="detail"), #<-------
    path('comment/<int:id>', views.comment, name="comment"),
]

User/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "User"

urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logoutUser, name="logout"),
]

TvShow/models.py
from django.db import models

# Create your models here.

class TvShow(models.Model): #Diziler tablosu
    title = models.CharField(max_length=150, verbose_name="Dizi Ad")
    kind = models.CharField(max_length=100, verbose_name="Tür")
    issue = models.CharField(max_length=800, verbose_name="Konu")
    year = models.CharField(max_length=10, verbose_name="Yıl")
    director = models.CharField(max_length=70, verbose_name="Yönetmen")
    performer = models.CharField(max_length=250, verbose_name="Oyuncular")
    season = models.CharField(max_length=30, verbose_name="Sezon Sayısı")
    imdbPoint = models.CharField(max_length=5, verbose_name="IMDB Puanı")
    link = models.CharField(max_length=200,verbose_name="Fragman")
    createdDate = models.DateTimeField(auto_now_add=True)
    seriesImage = models.FileField(blank=True, null=True, verbose_name="Dizinin Resmini Ekleyin")
    def __str__(self):
        return self.title
    #class Meta: #Son eklenenin en başa gelmesi için
    #    ordering = ['kind']

class Comment (models.Model):
    series = models.ForeignKey(TvShow, on_delete= models.CASCADE, verbose_name="Dizi", related_name="comments")
    username = models.ForeignKey("auth.User", on_delete= models.CASCADE, verbose_name="Kullanıcı")
    content = models.CharField(max_length= 500, verbose_name="Yorum")
    commentDate = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.content
    class Meta:
        ordering = ['-commentDate']

User/models.py
from django.db import models

# Create your models here.

User/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label="Kullanıcı Adı")
    password = forms.CharField(label="Şifre", widget=forms.PasswordInput)

class RegisterForm(forms.Form):
    first_name = forms.CharField(max_length=30, label="Ad")
    last_name = forms.CharField(max_length=50, label="Soyad")
    email = forms.CharField(max_length=100, label="E-Mail")
    username = forms.CharField(max_length=30, label="Kullanıcı Adı")
    password = forms.CharField(max_length=20, label="Şifre", widget=forms.PasswordInput)
    confirm = forms.CharField(max_length=20, label="Şifre Tekrar", widget=forms.PasswordInput)
    
    def clean(self):
        first_name = self.cleaned_data.get("first_name")
        last_name = self.cleaned_data.get("last_name")
        email = self.cleaned_data.get("email")
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")

        if(password and confirm and password != confirm):
            raise forms.ValidationError("Şifreler Eşleşmiyor...")
        
        values = {
            "first_name" : first_name,
            "last_name" : last_name,
            "email" : email,
            "username" : username,
            "password" : password
        }
        return values

TvShow/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404, reverse
from .models import TvShow, Comment

# Create your views here.

def index(request):
    keyword = request.GET.get("keyword")#arama yapmak için
    if keyword:
        series = TvShow.objects.filter(title__contains = keyword)
        return render(request, "index.html", {"series":series})
    series = TvShow.objects.all() #Autos veri tabanındaki tüm verileri sözlük yapısıyla aldık
    return render(request,"index.html",{"series":series})
 
def crime(request):
    series = TvShow.objects.filter(kind__contains = "Suç")
    return render(request,"crime.html",{"series":series})

def comedy(request):
    series = TvShow.objects.filter(kind__contains = "Komedi")
    return render(request,"comedy.html",{"series":series})

def mystery(request):
    series = TvShow.objects.filter(kind__contains = "Gizem")
    return render(request,"mystery.html",{"series":series})

def scifi(request):
    series = TvShow.objects.filter(kind__contains = "Bilim Kurgu")
    return render(request,"scifi.html",{"series":series})

def sport(request):
    series = TvShow.objects.filter(kind__contains = "Spor")
    return render(request,"sport.html",{"series":series})

def detail(request,id):
    series =get_object_or_404(TvShow, id = id)
    comments = series.comments.all()
    return render(request, "detail.html",{"series":series,"comments":comments})

def comment(request,id):
    series = get_object_or_404(TvShow, id = id)
    if request.method == "POST":
        username = request.user
        content = request.POST.get("content")

        newComment = Comment(username = username, content = content)
        newComment.series = series
        newComment.save()
    return redirect(reverse("TvShow:detail", kwargs={"id":id}))

User/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm, LoginForm
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from TvShow.models import TvShow

def register(request): 
    form = RegisterForm(request.POST or None)
    if(form.is_valid()): #forms.py'deki clean metodunu çağırdık
        first_name = form.cleaned_data.get("first_name")
        last_name = form.cleaned_data.get("last_name")
        email = form.cleaned_data.get("email")
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        newUser = User(username = username, first_name = first_name, last_name = last_name, email = email)
        newUser.set_password(password)
        newUser.save() #Kullanıcı Veri tabanına kaydedildi.
        login(request, newUser) #otomatik giriş yaptı
        messages.info(request,"Başarıyla Kayıt Oldunuz.")
        return redirect("index")
    context = {
        "form" : form
    }
    return render(request,"register.html", context)

def loginUser(request):
    form = LoginForm(request.POST or None)
    context = {
        "form" : form
    }
    if(form.is_valid()):
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        #Kullanıcı var mı sorgulamamız gerek. authenticate
        user = authenticate(username = username, password = password)
        if(user is None):
            messages.info(request,"Kullanıcı Adı veya Şifre Hatalı.")
            return render(request, "login.html", context)
        
        messages.info(request,"Hoş Geldiniz ")
        login(request,user)
        return redirect("index")

    return render(request,"login.html",context)

def logoutUser(request):
    logout(request)
    messages.info(request,"Hoşça kalın.")
    return redirect("index")

    

templates/comedy.html
{%extends "layout.html"%}

{%block title%}Komedi{%endblock title%}

{%block body%}


<hr>
<h3 style="text-align: center;" class="text-info">Komedi</h3>
<hr>

<!-- #Veri tabanında otomobil var mı onu kontrol etmek için -->
{%if series %} 
<div class="row">
{%for s in series %}

<div class="col-4">
<div class="card-group">
<div class="card bg-info mb-3" style="width: 18rem;">
  <img class="card-img-top" src="{{s.seriesImage.url}}" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">{{s.title}}</h5>
    <p>Oyuncular: {{s.performer}}</p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item bg-info">Tür:: {{s.kind}}</li>
      <li class="list-group-item bg-info">Sezon Sayısı: {{s.season}}</li>
      <li class="list-group-item bg-info">IMDB Puanı: {{s.imdbPoint}}</li>
  </ul>
  <div class="card-body">
    <a href="{% url 'TvShow:detail' s.id%}" class="btn btn-info">Detay</a>
  </div>
</div>
</div>
</div>
{% if forloop.counter|divisibleby:3 %}
</div>
<div class="row">
{%endif%}

{%endfor%}
{%else%}
<div class="alert alert-danger">Dizi Bulunamadı.</div>
{%endif%}

{%endblock body%}

templates/crime.html
{%extends "layout.html"%}

{%block title%}Suc{%endblock title%}

{%block body%}


<hr>
<h3 style="text-align: center;" class="text-info">Suç</h3>
<hr>

<!-- #Veri tabanında otomobil var mı onu kontrol etmek için -->
{%if series %} 
<div class="row">
{%for s in series %}

<div class="col-4">
<div class="card-group">
<div class="card bg-info mb-3" style="width: 18rem;">
  <img class="card-img-top" src="{{s.seriesImage.url}}" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">{{s.title}}</h5>
    <p>Oyuncular: {{s.performer}}</p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item bg-info">Tür:: {{s.kind}}</li>
      <li class="list-group-item bg-info">Sezon Sayısı: {{s.season}}</li>
      <li class="list-group-item bg-info">IMDB Puanı: {{s.imdbPoint}}</li>
  </ul>
  <div class="card-body">
    <a href="{% url 'TvShow:detail' s.id%}" class="btn btn-info">Detay</a>
  </div>
</div>
</div>
</div>
{% if forloop.counter|divisibleby:3 %}
</div>
<div class="row">
{%endif%}

{%endfor%}
{%else%}
<div class="alert alert-danger">Dizi Bulunamadı.</div>
{%endif%}

{%endblock body%}

templates/detail.html
{%extends "layout.html"%}

{%block title%}{{series.title}} {%endblock title%}

{%block body%}

<hr>
<h3 style="text-align: center;" class="text-info"> {{series.title}} </h3>
<h3 style="text-align: center;" class="text-info"><small>{{series.year}}</small></h3>
<hr>

<div class="text-center ">
   <img src="{{series.seriesImage.url}}" class="img-fluid" alt="Responsive image">
    <hr>
    <h5 class="text-white">{{series.issue}}</h5>

    <hr>

    <table class="table table-striped table-info">
        <tbody>
          <tr>
            <th scope="row">Tür</th>
            <td>{{series.kind}}</td>
          </tr>
          <tr>
            <th scope="row">Yönetmen</th>
            <td>{{series.director}}</td>
          </tr>
          <tr>
            <th scope="row">Oyuncular</th>
            <td>{{series.performer}}</td>
          </tr>
          <tr>
            <th scope="row">Sezon Sayısı</th>
            <td>{{series.season}}</td>
          </tr>
          <tr>
            <th scope="row">IMDB Puanı</th>
            <td>{{series.imdbPoint}}</td>
          </tr>
        </tbody>
      </table>
      <h4 style="text-align: center;" class="text-info"> Fragman</h4>
      <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="{{series.link}}"></iframe>
      </div>
</div>

<hr>
<div class="text-center">
    
</div>
<br>
<hr>
<br>
<div class="text-center">
    
    {% if request.user.is_authenticated %}
    <form method="POST" action="{% url 'TvShow:comment' series.id%}">
      {% csrf_token %}
      <div class="form-group">
        <label for="exampleFormControlTextarea1" class="text-white">Yorum Ekle</label>
        <textarea name="content" class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="Yorum Ekleyin"></textarea>
      </div>
      <button type="submit", class="btn btn-info">Yorum Yap</button>
    </form>  
    
    {% else %}
    <h5 class="text-white"><small>Yorum ekleyebilmek için <a href="{% url 'User:login'%}" class="text-white">giriş yapın.</a></small></h5>

    {% endif %} 
    </div>
    <div>
    <br><br>
    <h3 style="text-align: center;" class="text-info"> Yorumlar</h3>
    {% if comments %}
    
    <hr style="border-top:1px solid aqua;">
    {%for comment in comments%}
    <div class="media mb-4">
      <div class="media-body">
        <h5 class="text-info"> <small>{{comment.username}}</small> </h5>
        <h6 class="text-white"> <small>{{comment.content}}</small> </h6>
        <p class="text-white"> <small>{{comment.commentDate}}</small> </p>
      </div>
    </div>
    
    <hr style="border-top:1px solid aqua;">
    {%endfor%}
    {% else %}
    <div class="alert alert-info">Bu diziye yorum yazılmamış, ilk yorumu siz yapın.</div>

    {% endif %} 
    <br><br><br><br><br>    
    <br><br><br><br>
 </div>
{%endblock body%}

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="{% url 'index'%}">Ana Sayfa</a>
    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="navbar-collapse collapse" id="navbarColor01">
      <ul class="navbar-nav mr-auto">
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'TvShow:scifi'%}">Bilim Kurgu</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'TvShow:mystery'%}">Gizem</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'TvShow:comedy'%}">Komedi</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'TvShow:sport'%}">Spor</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'TvShow:crime'%}">Suç</a>
          </li>
      </ul>
      <ul class="navbar-nav ml-auto">

        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link text-info" href="{% url 'User:logout'%}">Çıkış Yap</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link text-info" href="{% url 'User:login'%}">Giriş Yap</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-info" href="{% url 'User:register'%}">Kayıt Ol</a>
        </li>
      {% endif %} 

      </ul>
      <form class="form-inline" method="GET" action="{% url 'index'%}">
        <div class="form-group">
        {%csrf_token%}
        <input class="form-control mr-sm-2" name="keyword" type="text" placeholder="Dizi Ara" aria-label="Search">
        <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Bul</button>
        </div>
      </form>
      
    </div>
  </nav>

templates/index.html
{%extends "layout.html"%}

{%block title%}Ana Sayfa{%endblock title%}

{%block body%}


<hr>
<h3 style="text-align: center;" class="text-info">Diziler</h3>
<hr>

<!-- #Veri tabanında otomobil var mı onu kontrol etmek için -->
{%if series %} 
<div class="row">
{%for s in series %}

<div class="col-4">
<div class="card-group">
<div class="card bg-info mb-3" style="width: 18rem;">
  <img class="card-img-top" src="{{s.seriesImage.url}}" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">{{s.title}}</h5>
    <p>Oyuncular: {{s.performer}}</p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item bg-info">Tür:: {{s.kind}}</li>
      <li class="list-group-item bg-info">Sezon Sayısı: {{s.season}}</li>
      <li class="list-group-item bg-info">IMDB Puanı: {{s.imdbPoint}}</li>
  </ul>
  <div class="card-body">
      <a href="{% url 'TvShow:detail' s.id%}" class="btn btn-info">Detay</a>
  </div>
</div>
</div>
</div>
{% if forloop.counter|divisibleby:3 %}
</div>
<div class="row">
{%endif%}

{%endfor%}
{%else%}
<div class="alert alert-danger">Dizi Bulunamadı.</div>
{%endif%}

{%endblock body%}

templates/layout.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{%block title%} {%endblock title%}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body style="background-color: rgb(21, 32, 43);">
    {%include "includes/navbar.html"%}

    <br>
    <div class="container">
<br>
            {% if messages %}
        <br><br>
                {% for message in messages %}
                <div class="alert alert-{{message.tags}}">{{message}}</div>
                {% endfor %}
            {% endif %}

        {%block body%}

        {%endblock body%}



        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        
    </div>
</body>
</html>

templates/login.html
{%extends "layout.html"%}

{%block title%}Giris Yap{%endblock title%}

{%block body%}
{% load crispy_forms_tags %}

<hr>
<h3 style="text-align: center;" class="text-info">Giriş Yap</h3>
<hr>
<div class="row" style="color:cadetblue;">
    <div class="col-md-6 offset-md-3">
        <form method="POST">
            {% csrf_token%}
            {{form|crispy}}
            <br>
            <button type="submit" class="btn btn-outline-info">Giriş Yap</button>
            <br>
            <br>
            <a href="{% url 'User:register'%}"><p class="text-info"><small>Hesap Oluştur</small> </p>  </a>
        </form>
    </div>
</div>

{%endblock body%}

templates/mystery.html
{%extends "layout.html"%}

{%block title%}Gizem{%endblock title%}

{%block body%}


<hr>
<h3 style="text-align: center;" class="text-info">Gizem</h3>
<hr>

<!-- #Veri tabanında otomobil var mı onu kontrol etmek için -->
{%if series %} 
<div class="row">
{%for s in series %}

<div class="col-4">
<div class="card-group">
<div class="card bg-info mb-3" style="width: 18rem;">
  <img class="card-img-top" src="{{s.seriesImage.url}}" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">{{s.title}}</h5>
    <p>Oyuncular: {{s.performer}}</p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item bg-info">Tür:: {{s.kind}}</li>
      <li class="list-group-item bg-info">Sezon Sayısı: {{s.season}}</li>
      <li class="list-group-item bg-info">IMDB Puanı: {{s.imdbPoint}}</li>
  </ul>
  <div class="card-body">
    <a href="{% url 'TvShow:detail' s.id%}" class="btn btn-info">Detay</a>
  </div>
</div>
</div>
</div>
{% if forloop.counter|divisibleby:3 %}
</div>
<div class="row">
{%endif%}

{%endfor%}
{%else%}
<div class="alert alert-danger">Dizi Bulunamadı.</div>
{%endif%}

{%endblock body%}

templates/register.html
{%extends "layout.html"%}

{%block title%}Kayıt Ol{%endblock title%}

{%block body%}
{% load crispy_forms_tags %}
<hr>
<h3 style="text-align: center;" class="text-info">Kayıt Ol</h3>
<hr>

<div class="row" style="color:cadetblue;">
        <div class="col-md-6 offset-md-3">
            <form method="POST">
                {% csrf_token%}
                {{form|crispy}}
                <br>
                <button type="submit" class="btn btn-outline-info">Kayıt Ol</button>
                <br>
                <br>
                <a href="{% url 'User:login'%}"><p class="text-info"><small>Giriş Yap</small> </p>  </a>
            </form>
        </div>
    </div>
    
{%endblock body%}

templates/scifi.html
{%extends "layout.html"%}

{%block title%}Bilim Kurgu{%endblock title%}

{%block body%}


<hr>
<h3 style="text-align: center;" class="text-info">Bilim Kurgu</h3>
<hr>

<!-- #Veri tabanında otomobil var mı onu kontrol etmek için -->
{%if series %} 
<div class="row">
{%for s in series %}

<div class="col-4">
<div class="card-group">
<div class="card bg-info mb-3" style="width: 18rem;">
  <img class="card-img-top" src="{{s.seriesImage.url}}" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">{{s.title}}</h5>
    <p>Oyuncular: {{s.performer}}</p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item bg-info">Tür:: {{s.kind}}</li>
      <li class="list-group-item bg-info">Sezon Sayısı: {{s.season}}</li>
      <li class="list-group-item bg-info">IMDB Puanı: {{s.imdbPoint}}</li>
  </ul>
  <div class="card-body">
    <a href="{% url 'TvShow:detail' s.id%}" class="btn btn-info">Detay</a>
  </div>
</div>
</div>
</div>
{% if forloop.counter|divisibleby:3 %}
</div>
<div class="row">
{%endif%}

{%endfor%}
{%else%}
<div class="alert alert-danger">Dizi Bulunamadı.</div>
{%endif%}

{%endblock body%}

templates/sport.html
{%extends "layout.html"%}

{%block title%}Spor{%endblock title%}

{%block body%}


<hr>
<h3 style="text-align: center;" class="text-info">Spor</h3>
<hr>

<!-- #Veri tabanında otomobil var mı onu kontrol etmek için -->
{%if series %} 
<div class="row">
{%for s in series %}

<div class="col-4">
<div class="card-group">
<div class="card bg-info mb-3" style="width: 18rem;">
  <img class="card-img-top" src="{{s.seriesImage.url}}" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">{{s.title}}</h5>
    <p>Oyuncular: {{s.performer}}</p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item bg-info">Tür:: {{s.kind}}</li>
      <li class="list-group-item bg-info">Sezon Sayısı: {{s.season}}</li>
      <li class="list-group-item bg-info">IMDB Puanı: {{s.imdbPoint}}</li>
  </ul>
  <div class="card-body">
    <a href="{% url 'TvShow:detail' s.id%}" class="btn btn-info">Detay</a>
  </div>
</div>
</div>
</div>
{% if forloop.counter|divisibleby:3 %}
</div>
<div class="row">
{%endif%}

{%endfor%}
{%else%}
<div class="alert alert-danger">Dizi Bulunamadı.</div>
{%endif%}

{%endblock body%}